Allow multiple storage classes
stackhpc/capi-helm-charts pull request #168
Opened 2023-12-04 01:28 UTC by heytrav

Rebase and small refactoring of #32

2023-12-04 10:11 UTC, mkjpryor commented on charts/cluster-addons/templates/openstack/csi-cinder.yaml
> +        volumeBindingMode: {{ .volumeBindingModea }}
Typo

2023-12-04 10:12 UTC, mkjpryor commented on charts/cluster-addons/templates/openstack/csi-cinder.yaml
> +{{- $rangeItem := . -}}
I think you can do this as

```
{{- range $rangeItem := .Values.openstack.csiCinder.additionalStorageClasses }}
```

??

2023-12-04 10:12 UTC, mkjpryor commented on charts/cluster-addons/templates/openstack/csi-cinder.yaml
> +{{- $storeageClassIndex := 0 }}
Typo

Also, what is this actually used for? As far as I can see it is incremented but never used.

2023-12-04 10:13 UTC, mkjpryor commented on charts/cluster-addons/templates/openstack/csi-cinder.yaml
> +{{- with $ }}
Is this actually necessary? I don't see any use of `.Values`, `.Chart`, etc. inside the loop?

2023-12-04 10:15 UTC, mkjpryor commented on charts/cluster-addons/values.yaml
> +      # allowedTopologies:
Please keep the same defaults as we had previously so as not to break existing installations that just use the defaults.

2023-12-04 15:00 UTC, mkjpryor requested changes
Sorry @heytrav - just a few more things that I missed the first time

2023-12-04 15:00 UTC, mkjpryor commented on charts/cluster-addons/values.yaml
> +      name: csi-cinder-fast
This should be just `csi-cinder` to match the old default

2023-12-04 15:00 UTC, mkjpryor commented on charts/cluster-addons/values.yaml
> +      #   # The reclaim policy for the storage class
This should document `volumeBindingMode` as being required for additional storage classes

2023-12-05 09:41 UTC, mkjpryor requested changes

2023-12-05 09:41 UTC, mkjpryor commented on charts/cluster-addons/values.yaml
> +    tag: # Defaults to chart appVersion if not given
This space is important for the linting

2023-12-13 16:02 UTC, mkjpryor commented
@heytrav Some changes were made to the cloud where we run the CI. Please can you rebase to pick up the required config changes?

2023-12-15 08:49 UTC, mkjpryor approved these changes
LGTM

2023-12-15 09:38 UTC, mkjpryor commented
@heytrav 

The chart upgrade test is failing with the following error:

```
Error: UPGRADE FAILED: cannot patch "csi-cinder" with kind StorageClass: StorageClass.storage.k8s.io "csi-cinder" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```

Looking at the patch, I think this is due to attempting to add `fstype: ext4` to the storage class. To be consistent with the previous setup, we need to not set this for the default storage class. I think the default is `ext4` anyway?

2023-12-15 09:41 UTC, mkjpryor commented
I feel like using the Kubernetes default fstype by default is the desired behaviour anyway, rather than the chart having an explicit opinion about it being `ext4`.

2023-12-15 09:42 UTC, mkjpryor requested changes

2023-12-15 09:42 UTC, mkjpryor commented on charts/cluster-addons/values.yaml
> +      fstype: ext4
Do not set a default here.

2023-12-15 09:54 UTC, heytrav commented on charts/cluster-addons/values.yaml
> +      fstype: ext4
Ok I removed ext4 as the default

2023-12-15 10:39 UTC, mkjpryor commented
@heytrav Did you mean to do all that other reformatting of the values file?

2023-12-15 17:19 UTC, heytrav commented
> @heytrav Did you mean to do all that other reformatting of the values file?

I didn't mean to no. My editor's linter settings are a bit too opinionated.

2023-12-15 23:10 UTC, mkjpryor approved these changes
LGTM subject to CI

2023-12-16 21:14 UTC, merged