Allow the specification of additional storage classes
stackhpc/capi-helm-charts pull request #32
Opened 2023-01-16 21:23 UTC by m-bull

Renames the `storageClass` to `defaultStorageClass`, and adds an `additionalStorageClasses` variable.

Useful for clouds that have multiple volume types with particular performance characteristics.

2023-01-24 14:20 UTC, scrungus approved these changes

2023-03-13 08:56 UTC, JohnGarbutt approved these changes

2023-10-31 03:01 UTC, heytrav commented
We would be keen this feature.

2023-10-31 09:24 UTC, mkjpryor requested changes
My only comment is can we do all the storage classes as different entries in a single manifests resource please?

2023-11-01 02:20 UTC, heytrav commented on charts/cluster-addons/templates/openstack/csi-cinder.yaml
> +        volumeBindingMode: WaitForFirstConsumer
Could we make this configurable? (same in `additionalStorageClasses`)

```yaml
volumeBindingMode: {{ .volumeBindingMode }}
```

2023-11-01 02:21 UTC, heytrav commented on charts/cluster-addons/templates/openstack/csi-cinder.yaml
> +          {{- end }}
Please add in `fstype` here (same in `additionalStorageclasses`)
```yaml
          {{- with .fstype }}
          fstype: {{ . }}
          {{- end }}

```

2023-11-01 08:00 UTC, m-bull commented
I'll try and fix this up this week - thanks for the reviews @heytrav and @mkjpryor

2023-11-14 19:57 UTC, heytrav commented
> My only comment is can we do all the storage classes as different entries in a single manifests resource please?

Just to clarify, would the idea be to put all the storageclasses into a single list and use an attribute like `default: true` to distinguish the default storageclass or would the helm chart still expect a `defaultStorageClass` and a list of `additionalStorageClasses`?

2023-11-15 10:21 UTC, mkjpryor commented
> > My only comment is can we do all the storage classes as different entries in a single manifests resource please?
> 
> Just to clarify, would the idea be to put all the storageclasses into a single list and use an attribute like `default: true` to distinguish the default storageclass or would the helm chart still expect a `defaultStorageClass` and a list of `additionalStorageClasses`?

I actually only meant to use a single `Manifests` resource for all the storage classes, not change the values interface, for now.

If we were to reduce it to just a single list I think we would want to refactor to have a `storageClassDefaults` + `storageClasses` list, and merge them - similar to how the node groups work - in order to retain control over the defaults in a way that overrides nicely. What I mean by that is overriding individual properties of specific list items is not really possible in Helm, so it would prevent us specifying sensible defaults unless we do this refactor.

So I would prefer that, if we do that, it comes in a separate patch.

2023-11-15 17:30 UTC, heytrav commented
> > > My only comment is can we do all the storage classes as different entries in a single manifests resource please?
> > 
> > 
> > Just to clarify, would the idea be to put all the storageclasses into a single list and use an attribute like `default: true` to distinguish the default storageclass or would the helm chart still expect a `defaultStorageClass` and a list of `additionalStorageClasses`?
> 
> I actually only meant to use a single `Manifests` resource for all the storage classes, not change the values interface, for now.

Thanks. That's what i expected but just wanted to confirm. I'm working on a function in magnum-capi-helm to pull the values out of cinder.

2023-11-15 18:00 UTC, mkjpryor commented
@heytrav That is good to hear because I wanted to implement that!

2023-12-16 22:47 UTC, closed without merging